### ISSUE TITLE
How to use this framework?

### ISSUE THREAD

**Issue by RamboWu** [madebykrol/RPG-demo-framework#1]
There is no .uproject file.

**Comment by madebykrol** [comment]
Hi!
Well, development of this sort of died off because of time constraints from
my work..

If you create a project from the TopDownExample template project in UE 4
you can use this "framework" as is by just dropping it inside of your
project "source" folder..

Actually, this is a git-repository of said folder inside a UE project.

<ProjectName>/Source/ [this repo]

If you wish I could rebase the repository to include all the solution and
project files..
I will however ignore Binaries/\* Build/\* Content/\* DerivedDataCache/*
Intermediate/\* and Saved/\* As these folders will make the projects size
exceede the limits of Github..

But if you just wish to take a look at the rather messy demo I made feel
free to create a project called TopDownExample and just drop this repo
inside the "Source" folder :)

2015-01-13 6:26 GMT+01:00 Rambo notifications@github.com:
